// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///

namespace BowlingARGame
{
public static class GPGSIDs
{
        public const string achievement_score = "CgkI9qmJl6gJEAIQAg"; // <GPGSID>
        public const string leaderboard_classic_mode_leaderboard = "CgkI9qmJl6gJEAIQCQ"; // <GPGSID>
        public const string achievement_play_with_a_friend = "CgkI9qmJl6gJEAIQBA"; // <GPGSID>
        public const string achievement_strike = "CgkI9qmJl6gJEAIQAw"; // <GPGSID>
        public const string achievement_bowling_champion = "CgkI9qmJl6gJEAIQBw"; // <GPGSID>
        public const string leaderboard_arcade_mode_leaderboard = "CgkI9qmJl6gJEAIQCg"; // <GPGSID>
        public const string achievement_finish_a_game_of_classic = "CgkI9qmJl6gJEAIQBQ"; // <GPGSID>
        public const string leaderboard_easy_mode_leaderboard = "CgkI9qmJl6gJEAIQCA"; // <GPGSID>
        public const string achievement_arcade = "CgkI9qmJl6gJEAIQBg"; // <GPGSID>

}
}
